### ISSUE TITLE
Tuesday October 18th -> Friday October 21st

### ISSUE THREAD

**Issue by GiupiDeLuca** [iotexproject/mini-challenges#3]
This week's challenge is about completing two functions: `removeAppliance()` and `toggleAppliance()`

The functions headers and a quick explanation are already provided below. All you have to do is make them work 😉

Happy Hacking! 🤖

```solidity
// SPDX-License-Identifier: SEE LICENSE IN LICENSE
pragma solidity ^0.8.17;

import "@openzeppelin/contracts/access/Ownable.sol";

// Represents any device connected to the Raspberry Pi that you want to control
struct Appliance {
    uint256 id;
    string name;
    bool status;
    bytes1 pin;
}

contract HomeAutomationDemo is Ownable {
    uint256 nextId = 1;
    uint256 count = 0;
    mapping(uint256 => Appliance) public appliances;

    // Add a new appliance to the list
    function addAppliance(string memory name, bytes1 pin) public onlyOwner {
        appliances[nextId] = Appliance(nextId, name, false, pin);
        nextId++;
        count++;
    }

    // Remove an appliance from the list
    function removeAppliance(uint256 id) public onlyOwner {
      // add your code here ...
    }

    // This is the function that will be called when the user 
    // toggles the status of the appliance on the mobile app
    function toggleAppliance(uint256 id) public onlyOwner {
        // add your code here ...
    }
```

**Comment by CarlSpobble** [comment]
function removeAppliance(uint256 id) public onlyOwner {
delete appliances[id];
count--;
}

function toggleAppliance(uint256 id) public onlyOwner {
require(appliances[id]!=0, "Device not registered or deleted");
if(appliances[id].status == false) { 
appliances[id].status = true;
} else {
appliances[id].status = false;
}
}

**Comment by GiupiDeLuca** [comment]
Thanks @CarlSpobble 

We were also thinking of this solution to toggle: 
```solidity
function toggleAppliance(uint256 id) public onlyOwner {
        appliances[id].status = !appliances[id].status;
    }
```

Good job and keep up the great work. Do you have a twitter handle to tag you in?

**Comment by CarlSpobble** [comment]
Hey @GiupiDeLuca yes your toggle appliance function is much easier 😮
You can tag me on Twitter at @cirque_du_nft 
Can't wait for the next challenges!
